name: course_weather_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  d_input: ^0.1.2
  d_method: ^0.2.4
  d_view: ^0.0.5
  equatable: ^2.0.5
  extended_image: ^8.2.0
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  grouped_list: ^5.1.2
  http: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mockito: ^5.4.4
  mocktail: ^1.0.2
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
